/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-11-06 00:37:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_005fUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>\r\n");
      out.write("        Watch movies\r\n");
      out.write("    </title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"contact.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"display: flex; justify-content: center; align-items: center; height: 80vh; background-color: rgb(0, 0, 0); color:white; font-size: xx-large;\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\" style=\"border: solid 5px black; padding: 50px;\">\r\n");
      out.write("        \r\n");
      out.write("       <h2>&#xf27b;CONTACT US</h2>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"form-main\">\r\n");
      out.write("        <div id=\"form-div\">\r\n");
      out.write("          <form class=\"montform\" id=\"reused_form\" action=\"prep_log_form.htm\">\r\n");
      out.write("            <p class=\"name\"> \r\n");
      out.write("                <input  style=\"font-size: large; width:57vh; padding: 20px ;\" name=\"name\" type=\"text\" class=\"feedback-input\" required placeholder=\"&#xf2b9; Enter your name\" id=\"name\" />\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"email\">\r\n");
      out.write("              <input  style=\"font-size: large;width:57vh; padding: 20px ;\" name=\"email\" type=\"email\" required  class=\"feedback-input\" id=\"email\" placeholder=\"&#xf0e0; Email\" />\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"text\">\r\n");
      out.write("              <textarea  style=\"font-size: large; width:57vh; padding: 20px ;\" name=\"message\" class=\"feedback-input\" id=\"comment\" placeholder=\"&#9829; We would love to hear from you.\"></textarea>\r\n");
      out.write("            </p>\r\n");
      out.write("            <div style=\"display: flex; justify-content: center; align-items: center;\">\r\n");
      out.write("                  <div class=\"submit\">\r\n");
      out.write("              <button  style=\"font-size: large; padding: 15px ; border-radius: 20px;\" type=\"submit\" class=\"button-blue\">SUBMIT</button>\r\n");
      out.write("              <div class=\"ease\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          </form>\r\n");
      out.write("                <div id=\"error_message\" style=\"width:100%; height:100%; display:none; \">\r\n");
      out.write("                      <h4>Error</h4>\r\n");
      out.write("                      Sorry there was an error sending your form.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"success_message\" style=\"width:100%; height:100%; display:none; \">\r\n");
      out.write("                <h2>Success! Your Message was Sent Successfully.</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
